# Generated by Django 3.1.3 on 2021-03-27 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20180210_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_birth',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 20, 24, 40, 81431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
